# UnityMol Copilot Architecture

## Overview

The UnityMol Copilot is designed to assist users with UnityMol visualization tasks by providing a natural language interface to the UnityMol API. The copilot will interpret user requests, generate appropriate UnityMol API calls, and execute them through the ZMQ communication channel provided by UnityMol.

## Components

### 1. Language Model Interface
- **Model**: DeepSeek-Coder-V2 (16B) via Ollama
- **Purpose**: Interpret natural language requests and generate appropriate UnityMol API calls
- **Implementation**: Python client for Ollama API

### 2. ZMQ Communication Layer
- **Purpose**: Send commands to UnityMol and receive results
- **Implementation**: PyZMQ library for communication with UnityMol's ZMQ server

### 3. FastAgent Integration
- **Purpose**: Provide an agentic framework for the copilot
- **Implementation**: Utilize FastAgent from mcp_agent.core.fastagent

### 4. Command Parser/Executor
- **Purpose**: Parse and execute commands generated by the language model
- **Implementation**: Python module to validate and format commands for ZMQ transmission

### 5. Response Handler
- **Purpose**: Process and format responses from UnityMol
- **Implementation**: Python module to parse JSON responses and present them to the user

### 6. Dual Mode Interface
- **Conversational Mode**: Direct interaction with users via natural language
- **MCP Tool Mode**: Integration with more complex agentic setups

## Data Flow

1. User provides a natural language request
2. FastAgent processes the request and sends it to the language model
3. Language model generates appropriate UnityMol API call(s)
4. Command parser validates and formats the commands
5. ZMQ communication layer sends commands to UnityMol
6. Response handler processes the JSON response
7. FastAgent presents the results to the user

## Technical Requirements

- Python 3.6+
- Ollama with DeepSeek-Coder-V2 model
- PyZMQ library
- FastAgent from mcp_agent.core.fastagent
- JSON parsing capabilities

## Implementation Considerations

- **Error Handling**: Robust error handling for both language model and ZMQ communication
- **Context Management**: Maintain context of previous commands for coherent interactions
- **API Coverage**: Support for all UnityMol API functions
- **Performance**: Optimize for response time while maintaining accuracy
- **Extensibility**: Design for easy addition of new UnityMol API functions
